defmodule Wayfarer.Dsl.HealthChecks do
  @moduledoc """
  A struct for storing a group of health-checks generated by the DSL.
  """

  alias Spark.Dsl.Entity
  alias Wayfarer.Dsl.HealthCheck

  defstruct __spark_metadata__: nil, health_checks: []

  @type t :: %__MODULE__{health_checks: [HealthCheck.t()]}

  @doc false
  @spec init :: t
  def init, do: %__MODULE__{health_checks: []}

  @doc false
  @spec entities :: [Entity.t()]
  def entities do
    [
      %Entity{
        name: :health_checks,
        target: __MODULE__,
        entities: [
          health_checks: HealthCheck.entities()
        ]
      }
    ]
  end
end
