defmodule Wayfarer.Dsl.HostPatterns do
  @moduledoc """
  A struct for storing a group of host patterns generated by the DSL.
  """

  alias Spark.Dsl.Entity
  alias Wayfarer.Dsl.HostPattern

  defstruct host_patterns: []

  @type t :: %__MODULE__{host_patterns: []}

  @doc false
  @spec init :: t
  def init, do: %__MODULE__{host_patterns: []}

  @doc false
  @spec entities :: [Entity.t()]
  def entities do
    [
      %Entity{
        name: :host_patterns,
        target: __MODULE__,
        entities: [
          host_patterns: HostPattern.entities()
        ]
      }
    ]
  end
end
